### ISSUE TITLE
[info needed] extract router model

### ISSUE THREAD

**Issue by rozxter1** [joshschmelzle/lswifi#27]
some wifi routers announce their model into beacon data. could it be parsed and added to json fields?

**Comment by joshschmelzle** [comment]
Can you take a look for `apname` key in JSON output or run lswifi with the `--ap-names` option to see if what you're requesting already exists?

The `--ap-names` option adds an `AP NAME` column to the printed ASCII table output. If you run `lswifi --ap-names` several times and no value is populated, either the AP is not advertising the name or I don't have a parser implemented for it.
