### ISSUE TITLE
Feature Request: STA channel bandwidth

### ISSUE THREAD

**Issue by lealog** [joshschmelzle/lswifi#4]
Hi,

Any possibility to implement a way to understand what is the channel bandwidth being used by the STA?
On linux we can check using the following command:

> i**w dev wlan0 info**
> Interface wlan0
>         ifindex 3
>         wdev 0x1
>         addr xx:xx:xx:xx:xx:xx
>         ssid xxxxxxxxxxxxxxx
>         type managed
>         wiphy 0
>         channel 36 (5180 MHz), **width: 40 MHz**, center1: 5190 MHz
>         txpower 31.00 dBm

**Comment by joshschmelzle** [comment]
Currently, there is a `--get-interfaces` argument that can be passed in, which gets information from [WlanQueryInterface](https://docs.microsoft.com/en-us/windows/win32/api/wlanapi/nf-wlanapi-wlanqueryinterface). See example output below. Unfortunately, this API does not return a channel width.

```
C:\Users\joshu>lswifi --get-interfaces
Interface: Intel(R) Wi-Fi 6E AX210 160MHz is connected
    Description: Intel(R) Wi-Fi 6E AX210 160MHz
    GUID: 00000000-0000-0000-0000-000000000000
    State: connected
    Connection Mode: profile
    Profile Name: Home-EAP
    SSID: Home-EAP
    BSSID: 00:4e:35:00:00:00
    BSS Type: Infra.
    PHY: HE
    Signal Quality: 84%
    Rx Rate: 961.0 Mbps
    Tx Rate: 1081.0 Mbps
    Security: Enabled
    .1X: Enabled
    Authentication: RSNA
    Cipher: CCMP
    Channel: 36
```

The only way to get the channel width is to initiate a scan, parse the response, and step through the information elements detected to calculate it.

When `--get-interfaces` is handled, lswifi does not initiate a scan. Some changes would be required to feed that back in.

What you might be looking for could be accomplished by running `lswifi --json` and redirecting output to PowerShell like this:

```
PowerShell 7.1.0
Copyright (c) Microsoft Corporation.

PS C:\Users\joshu> lswifi --json | ConvertFrom-JSON | Where-Object {$_.connected -like "true"} | Select-Object -Property bssid, ssid, channel_number, channel_width, rssi
2021-01-21 22:03:49,767 [INFO] lswifi.core: display filter sensitivity -82; output includes 22 of 23 BSSIDs detected in scan results.

bssid          : 00:4e:35:00:00:00
ssid           : Home-EAP
channel_number : 36
channel_width  : 80
rssi           : -55
```

Does this help?

**Comment by lealog** [comment]
Hi Josh,

Thanks.
I tried your command but the result is always the following:
```
lswifi.exe --json | ConvertFrom-JSON | Where-Object {$_.connected -like "true"} | Select-Object -Property bssid, ssid, channel_number, channel_width, rssi
2021-01-23 15:34:26,727 [INFO] lswifi.core: display filter sensitivity -82; displaying 20 of 22 BSSIDs detected in scan results:


bssid          :
ssid           :
channel_number :
channel_width  :
rssi           :
```

The command "**lswifi.exe --json | ConvertFrom-JSON**" is displaying the "connected" AP. It's seems the "**Where-Object {$_.connected -like "true"}**" is not filtering the right object.

**Comment by lealog** [comment]
Also did some tests and the parameter "channel_width" is always the one that AP is supporting. I changed my STA to connect only using 20MHz channel width and after a new "scan" using "lswifi.exe --json | ConvertFrom-JSON" the "channel_width" remains the same that AP supports and not the one being used by the STA on that moment. Do you think it's possible to have this information from the STA perspective?

**Comment by joshschmelzle** [comment]
> The command "lswifi.exe --json | ConvertFrom-JSON" is displaying the "connected" AP. It's seems the "Where-Object {$_.connected -like "true"}" is not filtering the right object.

This is a PowerShell bug depending on the PS version used, not a lswifi bug.

The example I gave works on PowerShell 7. On older version of PowerShell you will need to do something like this: 

```
(lswifi.exe --json | ConvertFrom-JSON) | Where-Object {$_.connected -like "true"} | Select-Object -Property bssid, ssid, channel_number, channel_width, rssi
```

See https://stackoverflow.com/questions/61477911/powershell-convertfrom-json-select-object-differences#61479214

**Comment by joshschmelzle** [comment]
> Also did some tests and the parameter "channel_width" is always the one that AP is supporting. I changed my STA to connect only using 20MHz channel width and after a new "scan" using "lswifi.exe --json | ConvertFrom-JSON" the "channel_width" remains the same that AP supports and not the one being used by the STA on that moment. Do you think it's possible to have this information from the STA perspective?

The channel width of an AP will always be based on scan results provided by wlanapi.h which consist of probe response, beacons, or both.

It's not possible to get channel width from a STAs perspective from the Native Wifi wlanapi.h. This requires writing a win32 filter driver.
